# Etapa de construcción
FROM node:16.13-alpine as builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

RUN npm install -g @angular/cli@14.2.11

COPY . .

EXPOSE 4200

CMD [ "ng", "serve", "--host", "0.0.0.0","--poll=1000" ]